name: Post Chapters

on:
  schedule:
    - cron: '5 * * * *'  # chạy mỗi giờ lúc phút 05
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install puppeteer-core

      - name: Run posting script
        env:
          BROWSERLESS_API_KEY: ${{ secrets.BROWSERLESS_API_KEY }}
        run: node script.js
